apiVersion: v1
kind: Service
metadata:
  name: app-go
  labels:
    app: app-go
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30001
  selector:
    app: app-go
    tier: frontend
