apiVersion: batch/v1
kind: Job
metadata:
  name: init-images
spec:
  template:
    spec:
      containers:
      - name: init-images
        image: alpine:3.15
        command: ['sh', '-c', "wget --no-check-certificate https://github.com/isucon/isucon9-qualify/releases/download/v2/initial.zip; unzip initial.zip; mkdir -p /public; rm -rf /public/upload; mv v3_initial_data /public/upload; rm initial.zip"]
        volumeMounts:
          - name: static-contents
            mountPath: /public
      volumes:
        - name: static-contents
          persistentVolumeClaim:
            claimName: isucon2-pv-claim
      restartPolicy: OnFailure
  backoffLimit: 2
