version: '3'

services:
  benchmarker:
    build: .
    hostname: benchmarker
    networks:
      default:
        ipv4_address: 172.20.0.100
    volumes:
      - ./initial-data:/home/isucon/isucari/initial-data
      - ./webapp/public:/home/isucon/isucari/webapp/public
    ports:
      - 5555:5555
      - 7000:7000
    entrypoint: "/app/bin/benchmark-worker"
    command: "-ep=http://portal:80 -benchmarker=/app/bin/benchmarker -payment-url=http://benchmarker:5555 -shipment-url=http://benchmarker:7000"
    environment:
      - CAMPAIGN_1000=2
      - CAMPAIGN_1130=3

networks:
  default:
    name: isucon9-qualify_default
    ipam:
      config:
        - subnet: 172.20.0.0/16
