version: '3'

services:
  benchmarker:
    build: .
    hostname: benchmarker
    networks:
      default:
        ipv4_address: 172.20.0.100
    volumes:
      - ./initial-data:/app/initial-data
      - ./webapp/public:/app/webapp/public
    ports:
      - 5555:5555
      - 7000:7000
    entrypoint: "/app/bin/benchmark-worker"
    command: "-ep=http://portal:80"

networks:
  default:
    name: isucon9-qualify_default
    ipam:
      config:
        - subnet: 172.20.0.0/16
