version: '3'

services:
  benchmarker:
    build: .
    hostname: benchmarker
    volumes:
      - ./initial-data:/app/initial-data
      - ./webapp/public:/app/webapp/public
    ports:
      - 5555:5555
      - 7000:7000
    command: "-target-url=http://app-ruby:8000 -payment-url=http://benchmarker:5555 -shipment-url=http://benchmarker:7000 -allowed-ips=172.20.0.10"

networks:
  default:
    name: isucon9-qualify_default
    ipam:
      config:
        - subnet: 172.20.0.0/16

